-- =============================================================================
-- PhishRadar - 01 : RBAC (modèle threat intelligence)
--   PR_ADMIN    : possède les objets, gère la plateforme
--   PR_ENGINEER : pipeline (ingestion, tasks) - c'est le rôle du script Python
--   PR_ANALYST  : analyste SOC - lit GOLD, ne voit pas RAW
--   PR_PARTNER  : partenaire externe - ne voit QUE la vue IOC sécurisée
-- =============================================================================
USE ROLE SECURITYADMIN;

CREATE ROLE IF NOT EXISTS PR_ADMIN;
CREATE ROLE IF NOT EXISTS PR_ENGINEER;
CREATE ROLE IF NOT EXISTS PR_ANALYST;
CREATE ROLE IF NOT EXISTS PR_PARTNER;

-- Hiérarchie : ADMIN > ENGINEER > ANALYST > PARTNER
GRANT ROLE PR_PARTNER  TO ROLE PR_ANALYST;
GRANT ROLE PR_ANALYST  TO ROLE PR_ENGINEER;
GRANT ROLE PR_ENGINEER TO ROLE PR_ADMIN;
GRANT ROLE PR_ADMIN    TO ROLE SYSADMIN;

USE ROLE ACCOUNTADMIN;
GRANT OWNERSHIP ON DATABASE PHISHRADAR TO ROLE PR_ADMIN COPY CURRENT GRANTS;

-- ENGINEER : tout sur RAW/SILVER, écriture sur GOLD, warehouse ingestion
GRANT USAGE ON DATABASE PHISHRADAR TO ROLE PR_ENGINEER;
GRANT ALL ON SCHEMA PHISHRADAR.RAW    TO ROLE PR_ENGINEER;
GRANT ALL ON SCHEMA PHISHRADAR.SILVER TO ROLE PR_ENGINEER;
GRANT ALL ON SCHEMA PHISHRADAR.GOLD   TO ROLE PR_ENGINEER;
GRANT USAGE ON WAREHOUSE WH_INGEST TO ROLE PR_ENGINEER;
GRANT EXECUTE TASK ON ACCOUNT TO ROLE PR_ENGINEER;

-- ANALYST : lecture GOLD uniquement + warehouse analytique
GRANT USAGE ON DATABASE PHISHRADAR TO ROLE PR_ANALYST;
GRANT USAGE ON SCHEMA PHISHRADAR.GOLD TO ROLE PR_ANALYST;
GRANT SELECT ON FUTURE TABLES IN SCHEMA PHISHRADAR.GOLD TO ROLE PR_ANALYST;
GRANT SELECT ON FUTURE VIEWS  IN SCHEMA PHISHRADAR.GOLD TO ROLE PR_ANALYST;
GRANT SELECT ON FUTURE DYNAMIC TABLES IN SCHEMA PHISHRADAR.GOLD TO ROLE PR_ANALYST;
GRANT USAGE ON WAREHOUSE WH_ANALYTICS TO ROLE PR_ANALYST;

-- PARTNER : rien ici - il n'accède qu'à la secure view (40) et au share (50)
GRANT USAGE ON DATABASE PHISHRADAR TO ROLE PR_PARTNER;
GRANT USAGE ON WAREHOUSE WH_ANALYTICS TO ROLE PR_PARTNER;
